extends:
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
plugins:
  - "@stylistic/stylelint-plugin"
  - stylelint-declaration-block-no-ignored-properties
rules:
  alpha-value-notation: null
  color-function-notation: null
  color-hex-length: null
  declaration-empty-line-before: null
  hue-degree-notation: null
  lightness-notation: null
  selector-class-pattern: ^[A-Z].*$
  "@stylistic/declaration-block-trailing-semicolon": always
  "@stylistic/indentation": 2
  "@stylistic/max-empty-lines": 1
  "@stylistic/no-eol-whitespace": true
  "@stylistic/no-extra-semicolons": true
  plugin/declaration-block-no-ignored-properties: true
  "scss/load-no-partial-leading-underscore": null
  order/properties-alphabetical-order: null
  order/properties-order:
    - 
      - 
        groupName: all-and-interact
        emptyLineBefore: never
        noEmptyLineBetween: true
        properties:
          - all
          - counter-set
          - counter-increment
          - counter-reset
          - pointer-events
          - touch-action
          - user-select
          - resize
          - cursor
          - color-scheme
      - 
        groupName: self-position
        emptyLineBefore: never
        noEmptyLineBetween: true
        properties:
          - quotes
          - content
          - order
          - visibility
          - flex
          - flex-grow
          - flex-shrink
          - flex-basis
          - place-self
          - justify-self
          - align-self
          - grid-area
          - grid-row
          - grid-row-start
          - grid-row-end
          - grid-column
          - grid-column-start
          - grid-column-end
          - column-span
          - position
          - float
          - clear
          - inset
          - inset-block
          - inset-block-start
          - inset-block-end
          - inset-inline
          - inset-inline-start
          - inset-inline-end
          - top
          - left
          - right
          - bottom
          - min-width
          - width
          - max-width
          - min-height
          - height
          - max-height
          - min-block-size
          - block-size
          - max-block-size
          - min-inline-size
          - inline-size
          - max-inline-size
          - line-height
          - aspect-ratio
          - break-before
          - break-inside
          - break-after
          - perspective-origin
          - perspective
          - transform-style
          - transform-origin
          - transform
          - translate
          - rotate
          - scale
          - z-index
      - 
        groupName: self-design
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - list-style
          - list-style-image
          - list-style-position
          - list-style-type
          - margin
          - margin-top
          - margin-left
          - margin-right
          - margin-bottom
          - margin-block
          - margin-block-start
          - margin-block-end
          - margin-inline
          - margin-inline-start
          - margin-inline-end
          - padding
          - padding-top
          - padding-left
          - padding-right
          - padding-bottom
          - padding-block
          - padding-block-start
          - padding-block-end
          - padding-inline
          - padding-inline-end
          - padding-inline-start
          - box-sizing
          - clip
          - clip-path
          - image-rendering
          - background
          - background-attachme
          - background-blend-mode
          - background-clip
          - background-color
          - background-image
          - background-origin
          - background-position
          - background-position
          - background-position
          - background-repeat
          - background-size
          - background
          - background-color
          - background-image
          - background-size
          - background-clip
          - background-repeat
          - background-origin
          - background-position
          - background-position-x
          - background-position-y
          - background-attachment
          - background-blend-mode
          - isolation
          - mix-blend-mode
          - filter
          - object-fit
          - object-position
          - opacity
          - box-shadow
          - border
          - border-top
          - border-left
          - border-right
          - border-bottom
          - border-width
          - border-top-width
          - border-left-width
          - border-right-width
          - border-bottom-width
          - border-style
          - border-top-style
          - border-left-style
          - border-right-style
          - border-bottom-style
          - border-color
          - border-top-color
          - border-left-color
          - border-right-color
          - border-bottom-color
          - border-radius
          - border-top-left-radius
          - border-top-right-radius
          - border-bottom-left-radius
          - border-bottom-right-radius
          - border-start-start-radius
          - border-start-end-radius
          - border-end-start-radius
          - border-end-end-radius
          - border-block
          - border-block-start
          - border-block-end
          - border-block-width
          - border-block-start-width
          - border-block-end-width
          - border-block-style
          - border-block-start-style
          - border-block-end-style
          - border-block-color
          - border-block-start-color
          - border-block-end-color
          - border-inline
          - border-inline-start
          - border-inline-end
          - border-inline-width
          - border-inline-start-width
          - border-inline-end-width
          - border-inline-style
          - border-inline-start-style
          - border-inline-end-style
          - border-inline-color
          - border-inline-start-color
          - border-inline-end-color
          - border-image
          - border-image-source
          - border-image-slice
          - border-image-width
          - border-image-outset
          - border-image-repeat
          - border-spacing
          - border-collapse
          - outline
          - outline-width
          - outline-style
          - outline-color
          - outline-offset
          - backdrop-filter
          - box-decoration-break
          - backface-visibility
          - fill
          - stroke
          - marker
          - marker-start
          - marker-mid
          - marker-end
          - paint-order
          - mask-image
          - mask-mode
          - mask-origin
          - mask-position
          - mask-repeat
          - mask-size
          - transition
          - transition-property
          - transition-duration
          - transition-delay
          - transition-timing-function
          - animation
          - animation-duration
          - animation-timing-function
          - animation-delay
          - animation-iteration-count
          - animation-direction
          - animation-fill-mode
          - animation-play-state
          - animation-name
          - offset
          - offset-path
          - offset-distance
          - offset-rotate
          - offset-anchor
      - 
        groupName: child-position
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - display
          - flex-flow
          - flex-direction
          - flex-wrap
          - place-content
          - justify-content
          - align-content
          - place-items
          - justify-items
          - align-items
          - grid
          - grid-template
          - grid-template-areas
          - grid-template-rows
          - grid-template-columns
          - grid-auto-flow
          - grid-auto-rows
          - grid-auto-columns
          - gap
          - row-gap
          - column-gap
          - column-fill
          - widows
          - columns
          - column-count
          - column-width
          - column-rule
          - column-rule-style
          - column-rule-width
          - column-rule-color
          - orphans
          - overflow
          - overflow-x
          - overflow-y
          - overflow-wrap
          - overflow-anchor
          - overscroll-behavior
          - overscroll-behavior-x
          - overscroll-behavior-y
          - overscroll-behavior-block
          - overscroll-behavior-inline
          - scroll-behavior
          - scroll-margin
          - scroll-margin-block
          - scroll-margin-block-start
          - scroll-margin-block-end
          - scroll-margin-inline
          - scroll-margin-inline-start
          - scroll-margin-inline-end
          - scroll-margin-top
          - scroll-margin-left
          - scroll-margin-right
          - scroll-margin-bottom
          - scroll-padding
          - scroll-padding-block
          - scroll-padding-block-start
          - scroll-padding-block-end
          - scroll-padding-inline
          - scroll-padding-inline-start
          - scroll-padding-inline-end
          - scroll-padding-top
          - scroll-padding-left
          - scroll-padding-right
          - scroll-padding-bottom
          - scroll-snap-align
          - scroll-snap-stop
          - scroll-snap-type
          - table-layout
          - caption-side
          - empty-cells
      - 
        groupName: child-design
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - unicode-bidi
          - direction
          - writing-mode
          - text-align
          - text-align-last
          - text-justify
          - vertical-align
          - white-space
          - text-wrap
          - word-break
          - word-spacing
          - letter-spacing
          - tab-size
          - text-indent
          - hyphens
          - hyphenate-character
          - hanging-punctuation
          - text-overflow
          - initial-letter
          - text-transform
          - text-orientation
          - font
          - font-style
          - font-feature-settings
          - font-variant
          - font-variant-ligatures
          - font-variant-alternates
          - font-variant-caps
          - font-variant-numeric
          - font-variant-east-asian
          - font-weight
          - font-stretch
          - font-size
          - font-size-adjust
          - font-family
          - font-kerning
          - color
          - accent-color
          - caret-color
          - scrollbar-color
          - text-shadow
          - text-decoration
          - text-decoration-line
          - text-decoration-style
          - text-decoration-color
          - text-decoration-thickness
          - text-underline-offset
          - text-underline-position
          - text-emphasis
          - text-emphasis-style
          - text-emphasis-color
          - text-emphasis-position
    -
      unspecified: bottomAlphabetical
      emptyLineBeforeUnspecified: always
